### ISSUE TITLE
Docker first steps - Alejandro

### ISSUE THREAD

**Issue by dan-castillo** [dan-castillo/Paynallitest#10]
want to start using docker at a very high level

use these links to start
video one
https://www.youtube.com/watch?v=Kyx2PsuwomE
video two
https://www.youtube.com/watch?v=hP77Rua1E0c&t=965s

**Comment by arkzky** [comment]
Recieved. I'll update this task when finished.

**Comment by LigiaZC** [comment]
Received, but I have a question.
Do I have to implement all the codes for myself o this is just so I can see
what you guys are doing ?
Because I really  don't understand the terminology and the codes and how to
put them.
Thank you
Ligia

**Comment by arkzky** [comment]
This task is done.
