### ISSUE TITLE
Set up Nodejs API Sample

### ISSUE THREAD

**Issue by dan-castillo** [dan-castillo/Paynallitest#3]
this will take two points
this s part of an epic covered by issue #1

**Comment by arkzky** [comment]
### Section 3: Node Js API
- [ ] Moving Routes 
- [ ] Moving to controllers
- [ ] User model
- [ ] Applying middlewares
- [ ] MongoDB Atlas Robo3T and Postman
- [ ] Connect to mongoDB

**Comment by dan-castillo** [comment]
Alejandro, please use NodeSql Booster instead of Robot3T

https://nosqlbooster.com/home

**Comment by arkzky** [comment]
This task it's done. I'm going to comment on every task that it's currently in the same situation. Thanks for the feedback Dan
