### ISSUE TITLE
Install Mongo docker image - Alejandro

### ISSUE THREAD

**Issue by dan-castillo** [dan-castillo/Paynallitest#30]

**Comment by dan-castillo** [comment]
this links shows how to set up a volume
https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

**Comment by arkzky** [comment]
Apparently Docker can't find the javascript file where the user and database is created. This is due to some path problems incompatibilities with Windows.

**Comment by arkzky** [comment]
This task is done.
