### ISSUE TITLE
Setup NodeJs server

### ISSUE THREAD

**Issue by dan-castillo** [dan-castillo/Paynallitest#4]
this is linked to an Epic covered in issue #2

**Comment by hector-gomez-aranda** [comment]
- [ ] Section 1 Course Introduction
- [ ] 1.1 Introduction

- [ ] Section 2 Getting Started
- [ ] 2.1 Setup client
- [ ] 2.2 Setup Server
- [ ] 2.3 Installing NPM packages

- [ ] Section 3 Node Js API
- [ ] 3.1 Moving routes
- [ ] 3.2 Moving to controllers
- [ ] 3.3 User model
- [ ] 3.4 Appling middlewares
- [ ] 3.5 MongoDB Atlas Robo3T and Postman
- [ ] 3.6 Connect to mongodb

**Comment by dan-castillo** [comment]
please use no sql booster instead of Robo 3T - 

https://nosqlbooster.com/home

**Comment by hector-gomez-aranda** [comment]
I finished this task
